name: Python application

on:
  workflow_dispatch:
  schedule:
  - cron:  "0 8 * * *" 

env:

  GITHUB_USER_NAME: mill413
  GITHUB_USER_EMAIL: mill413@outlook.com

permissions:
  contents: read

jobs:
  build:
    name: update
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Python Env
      uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.12'
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run daily arxiv 
      run: |
        python main.py
        
    - name: Push new index.md
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Github Action Automatic Update Arxiv Papers"
        files: index.md
        rebase: 'true'
        name: ${{ env.GITHUB_USER_NAME }}
        email: ${{ env.GITHUB_USER_EMAIL }}
